/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as walletSol from "./Wallet.sol";
export type { walletSol };
export type { Julia } from "./Julia";
export type { TokenWallet } from "./TokenWallet";
export type { Vault } from "./Vault";
